# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# C:\b\abs_1bvnmbomf8\clone\recipe, last modified Wed Sep 18 17:44:45 2024
# ------------------------------------------------

package:
  name: setuptools
  version: 75.1.0
source:
  patches:
    - patches/0002-disable-downloads-inside-conda-build.patch
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
  sha256: d59a21b17a275fb872a9c3dae73963160ae079f1049ed956880cd7c09b120538
  url: https://pypi.io/packages/source/s/setuptools/setuptools-75.1.0.tar.gz
build:
  missing_dso_whitelist:
    - $RPATH/MSVCR71.dll
    - $RPATH/MSVCR80.dll
  number: '0'
  string: py311haa95532_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.7.2 haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - python 3.11.9 he1021f5_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024a h04d1e81_0
    - vc 14.40 h2eaa2aa_1
    - vs2015_runtime 14.40.33807 h98bb1dd_1
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - python >=3.11,<3.12.0a0
test:
  commands:
    - pip check
  imports:
    - pkg_resources
    - setuptools
  requires:
    - pip
about:
  description: 'Setuptools is a fully-featured, actively-maintained, and stable library

    designed to facilitate packaging Python projects.

    '
  dev_url: https://github.com/pypa/setuptools
  doc_url: https://setuptools.pypa.io
  home: https://github.com/pypa/setuptools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1b2ec7a4-26bb-4c55-8a64-3f6d13ec3e6d
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - nicoddemus
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/setuptools-feedstock.git
  sha: 985bc6bdb5383b20ddaed7635f95bd2858b25902
  skip-lints:
    - missing_python_build_tool
    - missing_wheel
