# Generated by Django 5.1.3 on 2024-12-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("selling_price", models.FloatField()),
                ("discount_price", models.FloatField()),
                ("descripition", models.TextField()),
                ("composition", models.TextField(default="")),
                ("prodapp", models.TextField(default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CR", "curd"),
                            ("MK", "milk"),
                            ("LS", "Laasi"),
                            ("MS", "Milkshake"),
                            ("PN", "paneer"),
                            ("GH", "Ghee"),
                            ("CH", "chesse"),
                            ("IC", "Ice-cream"),
                        ],
                        max_length=2,
                    ),
                ),
                ("Product_image", models.ImageField(upload_to="Product")),
            ],
        ),
    ]
