# Generated by Django 5.1.3 on 2024-12-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="quanity",
        ),
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
