# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: python
  version: 3.11.10
source:
  - patches:
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
      - patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0006-Win32-Do-not-download-externals.patch
      - patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0010-Unvendor-openssl.patch
      - patches/0011-Unvendor-sqlite3.patch
      - patches/0012-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0014-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
      - patches/0015-Doing-d1trimfile.patch
      - patches/0016-cross-compile-darwin.patch
      - patches/0017-Fix-TZPATH-on-windows.patch
      - patches/0018-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0019-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
      - patches/0020-Unvendor-bzip2.patch
      - patches/0021-Unvendor-libffi.patch
      - patches/0022-Unvendor-tcltk.patch
      - patches/0023-unvendor-xz.patch
      - patches/0024-unvendor-zlib.patch
      - patches/0025-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
    sha256: 07a4356e912900e61a15cb0949a06c4a05012e213ecd6b4e84d0f67aabbee372
    url: https://www.python.org/ftp/python/3.11.10/Python-3.11.10.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  missing_dso_whitelist:
    - '**/MSVCR71.dll'
    - '**/MSVCR80.dll'
    - '**/api-ms-win-core-path-l1-1-0.dll'
  no_link:
    - DLLs/_ctypes.pyd
  number: 0
  script_env:
    - CONDA_FORGE=no
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  string: h4607a30_0
requirements:
  build:
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.9.24 haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - vc 14.40 h2eaa2aa_1
    - vs2015_runtime 14.40.33807 h98bb1dd_1
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libffi >=3.4,<3.5
    - libffi >=3.4,<4.0a0
    - openssl >=3.0.15,<4.0a0
    - sqlite >=3.45.3,<4.0a0
    - tk >=8.6.14,<8.7.0a0
    - tzdata
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
    - xz >=5.4.6,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - echo on
    - set
    - python -V
    - 2to3 -h
    - pydoc -h
    - set "PIP_NO_BUILD_ISOLATION=False"
    - set "PIP_NO_DEPENDENCIES=True"
    - set "PIP_IGNORE_INSTALLED=True"
    - set "PIP_NO_INDEX=True"
    - set "PIP_CACHE_DIR=%CONDA_PREFIX%/pip_cache"
    - set "TEMP=%CONDA_PREFIX%/tmp"
    - mkdir "%TEMP%"
    - python -Im ensurepip --upgrade --default-pip
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - test-venv\\Scripts\\python.exe -c "import ctypes"
    - if exist %PREFIX%\\Scripts\\pydoc exit 1
    - if exist %PREFIX%\\Scripts\\idle exit 1
    - if exist %PREFIX%\\Scripts\\2to3 exit 1
    - if not exist %PREFIX%\\Scripts\\pydoc-script.py exit 1
    - if not exist %PREFIX%\\Scripts\\idle-script.py exit 1
    - if not exist %PREFIX%\\Scripts\\2to3-script.py exit 1
    - if not exist %PREFIX%\\Scripts\\idle.exe exit 1
    - if not exist %PREFIX%\\Scripts\\2to3.exe exit 1
    - if not exist %PREFIX%\\Scripts\\pydoc.exe exit 1
    - if not exist %PREFIX%\\libs\\python311.lib exit 1
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.11.10
    - popd
    - popd
    - python run_test.py
    - python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils/*
    - tests/prefix-replacement/*
  requires:
    - cmake-no-system
    - ninja-base
    - ripgrep
    - vs2019_win-64
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://devguide.python.org/
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  license_url: https://spdx.org/licenses/PSF-2.0.html
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  flow_run_id: 57d208bc-a4a5-4fe7-af92-0149b73de27b
  recipe-maintainers:
    - isuruf
    - jakirkham
    - katietz
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/python-feedstock.git
  sha: 6ddc0451efec9ec277348eb57725290088d7a16a
