# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# C:\b\abs_9btgg364vx\clone\recipe, last modified Mon Aug 12 18:50:24 2024
# ------------------------------------------------

package:
  name: pip
  version: '24.2'
source:
  sha256: 5b5e490b5e9cb275c879595064adce9ebd31b854e3e803740b72f9ccf34a45b8
  url: https://pypi.io/packages/source/p/pip/pip-24.2.tar.gz
build:
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main
  number: '0'
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.7.2 haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.14 h827c3e9_0
    - python 3.11.9 he1021f5_0
    - setuptools 72.1.0 py311haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024a h04d1e81_0
    - vc 14.40 h2eaa2aa_0
    - vs2015_runtime 14.40.33807 h98bb1dd_0
    - wheel 0.43.0 py311haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - python >=3.11,<3.12.0a0
    - setuptools
    - wheel
test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip
about:
  description: 'pip is the package installer for Python.

    You can use pip to install packages from the Python Package

    Index and other indexes.

    '
  dev_url: https://github.com/pypa/pip
  doc_url: https://pip.pypa.io
  home: https://pip.pypa.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9b64720f-f901-476a-9ec7-0f0fa2180278
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/pip-feedstock.git
  sha: a02d490e338bfcd82432374562a35521dbd44e24
  skip-lints:
    - missing_pip_check
    - python_build_tool_in_run
    - uses_setup_py
