# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_17sr80_iza\clone\recipe, last modified Fri May  3 22:09:39 2024
# ------------------------------------------------

package:
  name: tk
  version: 8.6.14
source:
  - folder: tcl8.6.14
    patches:
      - 0002-win-unvendor-zlib.patch
    sha256: 5880225babf7954c58d4fb0f5cf6279104ce1cd6aa9b71e9a6322540e1c4de66
    url: https://altushost-swe.dl.sourceforge.net/project/tcl/Tcl/8.6.14/tcl8.6.14-src.tar.gz
  - folder: tk8.6.14
    sha256: 8ffdb720f47a6ca6107eac2dd877e30b0ef7fac14f3a84ebbd0b3612cee41a94
    url: https://altushost-swe.dl.sourceforge.net/project/tcl/Tcl/8.6.14/tk8.6.14-src.tar.gz
build:
  detect_binary_files_with_prefix: true
  number: '0'
  run_exports:
    - tk >=8.6.14,<8.7.0a0
  string: h0416ee5_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2019_win-64 19.27.29111 ha89c4d3_2
    - vswhere 2.8.4 haa95532_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.13 h8cc25b3_1
  run:
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.27.29016,<15.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\wish.exe exit 1
    - if not exist %LIBRARY_PREFIX%\\bin\\tclsh.exe exit 1
    - if not exist %LIBRARY_PREFIX%\\bin\\wish86.exe exit 1
    - if not exist %LIBRARY_PREFIX%\\bin\\tclsh86.exe exit 1
    - if not exist %LIBRARY_PREFIX%\\include\\tcl.h exit 1
    - if not exist %LIBRARY_PREFIX%\\include\\tclDecls.h exit 1
    - if not exist %LIBRARY_PREFIX%\\include\\tclPlatDecls.h exit 1
    - if not exist %LIBRARY_PREFIX%\\include\\tclPlatDecls.h exit 1
    - if not exist %LIBRARY_PREFIX%\\include\\tclTomMathDecls.h exit 1
    - if not exist %LIBRARY_PREFIX%\\include\\tclTomMath.h exit 1
    - if not exist %LIBRARY_PREFIX%\\include\\tk.h exit 1
    - if not exist %LIBRARY_PREFIX%\\include\\tkDecls.h exit 1
    - if not exist %LIBRARY_PREFIX%\\include\\tkPlatDecls.h exit 1
    - if not exist %LIBRARY_PREFIX%\\lib\\tcl86t.lib exit 1
    - if not exist %LIBRARY_PREFIX%\\bin\\tcl86t.dll exit 1
    - if not exist %LIBRARY_PREFIX%\\lib\\tclstub86.lib exit 1
    - if not exist %LIBRARY_PREFIX%\\lib\\tk86t.lib exit 1
    - if not exist %LIBRARY_PREFIX%\\bin\\tk86t.dll exit 1
    - if not exist %LIBRARY_PREFIX%\\lib\\tkstub86.lib exit 1
    - tclsh hello.tcl
    - tclsh86 hello.tcl
    - wish hello.tcl
    - wish86t hello.tcl
  files:
    - hello.tcl
about:
  description: 'Tcl (Tool Command Language) is a very powerful but easy to learn dynamic
    programming language,

    suitable for a very wide range of uses, including web and desktop applications,
    networking,

    administration, testing and many more. Open source and business-friendly,

    Tcl is a mature yet evolving language that is truly cross platform, easily deployed
    and highly extensible.

    Tk is a graphical user interface toolkit that takes developing desktop applications
    to a higher level than

    conventional approaches. Tk is the standard GUI not only for Tcl, but for many
    other dynamic languages,

    and can produce rich, native applications that run unchanged across Windows, Mac
    OS X, Linux and more.

    '
  dev_url: https://core.tcl-lang.org/tk/home
  doc_url: https://www.tcl.tk/man/tcl8.6/index.html
  home: https://www.tcl.tk/
  license: TCL
  license_family: BSD
  license_file: tcl8.6.14/license.terms
  summary: A dynamic programming language with GUI support. Bundles Tcl and Tk.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 172cd0ac-4d15-4545-9e6d-f2e1653e8c91
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/tk-feedstock.git
  sha: 7e6bf85c7160a89134e176b5ddd1ead57e12cade
