# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_408t8wz0h8\clone\recipe, last modified Tue Apr 30 23:04:42 2024
# ------------------------------------------------

package:
  name: xz
  version: 5.4.6
source:
  sha256: 913851b274e8e1d31781ec949f1c23e8dbcf0ecf6e73a2436dc21769dd3e6f49
  url: https://github.com/tukaani-project/xz/releases/download/v5.4.6/xz-5.4.6.tar.bz2
build:
  number: '1'
  run_exports:
    - xz >=5.4.6,<6.0a0
  string: h8cc25b3_1
requirements:
  build:
    - m2-base 1.0.0 3
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-diffutils 3.3 4
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libbz2 1.0.6 3
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-make 4.1 5
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-sed 4.2.2 3
    - m2-tar 1.28 4
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-unzip 6.0 3
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zip 3.0 2
    - m2-zlib 1.2.8 4
    - m2w64-binutils 2.25.1 5
    - m2w64-bzip2 1.0.6 6
    - m2w64-crt-git 5.0.0.4636.2595836 2
    - m2w64-gcc 5.3.0 6
    - m2w64-gcc-ada 5.3.0 6
    - m2w64-gcc-fortran 5.3.0 6
    - m2w64-gcc-libgfortran 5.3.0 6
    - m2w64-gcc-libs 5.3.0 7
    - m2w64-gcc-libs-core 5.3.0 7
    - m2w64-gcc-objc 5.3.0 6
    - m2w64-gmp 6.1.0 2
    - m2w64-headers-git 5.0.0.4636.c0ad18a 2
    - m2w64-isl 0.16.1 2
    - m2w64-libiconv 1.14 6
    - m2w64-libmangle-git 5.0.0.4509.2e5a9a2 2
    - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
    - m2w64-make 4.1.2351.a80a8b8 2
    - m2w64-mpc 1.0.3 3
    - m2w64-mpfr 3.1.4 4
    - m2w64-pkg-config 0.29.1 2
    - m2w64-toolchain 5.3.0 7
    - m2w64-tools-git 5.0.0.4592.90b8472 2
    - m2w64-windows-default-manifest 6.4 3
    - m2w64-winpthreads-git 5.0.0.4634.697f757 2
    - m2w64-zlib 1.2.8 10
    - msys2-conda-epoch 20160418 1
    - posix 1.0.0 2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - xz.exe --help
    - unxz.exe --help
    - if not exist %PREFIX%\\Library\\bin\\liblzma.dll exit 1
    - if not exist %PREFIX%\\Library\\lib\\liblzma.lib exit 1
    - if not exist %PREFIX%\\Library\\lib\\liblzma_static.lib exit 1
    - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\liblzma.pc exit 1
    - if not exist %PREFIX%\\Library\\include\\lzma.h exit 1
    - if not exist %PREFIX%\\Library\\bin\\xz.exe exit 1
    - if exist %PREFIX%\\lib exit 1
  requires: null
about:
  description: 'XZ Utils is free general-purpose data compression software with a
    high

    compression ratio. XZ Utils were written for POSIX-like systems, but also

    work on some not-so-POSIX systems.

    '
  dev_url: https://github.com/tukaani-project/xz
  doc_url: https://tukaani.org/xz/
  home: https://xz.tukaani.org/xz-utils/
  license: LGPL-2.1-or-later and GPL-2.0-or-later and 0BSD
  license_family: GPL2
  license_file: COPYING
  summary: Data compression software with high compression ratio
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 40fbf6e7-cc0e-4bca-897e-f941f885c092
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/xz-feedstock.git
  sha: e4727181dd6dd975f850faa66a9233fd6773eac8
